spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name:microservicecloud-config-sj-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-sj-test
#保存为utf-8